name: Node CI
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Use Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install yarn
        run: npm install -g yarn
      - name: yarn install, build, and test
        run: |
          yarn install  --frozen-lockfile
          yarn build
